sitelogistic/sitelogistic/urls.py
# import threading
# from django.urls import path, include
# from trade_logistic import views
# from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from trade_logistic.views import page_not_found
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trade_logistic.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Руководство по работе с сайтом'

sitelogistic/trade_logistic/urls.py
from django.urls import path, re_path, register_converter, include

from . import views
from . import converters
from .views import *

register_converter(converters.FourDigitYearConverter, "year4")

urlpatterns = [
    # path('', views.index, name='home'),
    path('', TradeLogisticHome.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('get-exel/', views.get_excel, name='get_excel'),
    path('add-page/', AddPage.as_view(), name='add_page'),
    path('contact/', views.contact, name='contact'),
    path('upload-file/', views.upload_file, name='upload_file'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('post/<slug:post_slug>/', ShowPost.as_view(), name='post'),
    path('category/<slug:cat_slug>/', TradeLogisticCategory.as_view(), name='category'),
    path('tag/<slug:tag_slug>/', views.show_tag_postlist, name='tag'),
    # path('doc-info/', views.get_doc_info, name='doc_info'),
    path('doc-info/', DocsListView.as_view(), name='doc_info'),
    path('download/<str:path_doc>/', views.download, name='download'),
    path('erip-info/', views.erip_info, name='erip_info'),
    path('happy-birthdays/', views.show_happy_birthdays, name='happy_birthdays')
]

sitelogistic/trade_logistic/models.py
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
from transliterate import translit


def my_slugify(text):
    return slugify(translit(text, 'ru', reversed=True))


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=TradeLogistic.Status.PUBLISHED)


class TradeLogistic(models.Model):
    class Status(models.IntegerChoices):
        DRAFT = 0, 'Черновик'
        PUBLISHED = 1, 'Опубликовано'

    class Meta:
        verbose_name = 'Торговая логистика'
        verbose_name_plural = 'Торговая логистика'
        ordering = ['time_create']  # для обратного эффекта поставить '-'
        indexes = [models.Index(fields=['-time_create'])]

    title = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='Слаг',
                            validators=[
                                MinLengthValidator(5, 'Минимум 5 символов'),
                                MaxLengthValidator(100, 'Максимум 100 символов')
                            ])
    content = models.TextField(blank=True, verbose_name='Содержание')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    is_published = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)),
                                       default=Status.PUBLISHED, verbose_name='Статус')
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='posts', verbose_name='Категории')
    tags = models.ManyToManyField('TagPost', related_name='tags', verbose_name='Теги')
    note = models.OneToOneField('Note', on_delete=models.SET_NULL, null=True, blank=True, related_name='post',
                                verbose_name='Примечание')
    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = my_slugify(self.title)
        super().save(*args, **kwargs)


class Category(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    name = models.CharField(max_length=100, db_index=True, verbose_name='Категории')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='Слаг')
    objects = models.Manager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})


class TagPost(models.Model):
    class Meta:
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'

    tag = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    objects = models.Manager()

    def __str__(self):
        return self.tag

    def get_absolute_url(self):
        return reverse('tag', kwargs={'tag_slug': self.slug})


class Note(models.Model):
    class Meta:
        verbose_name = 'Примечание'
        verbose_name_plural = 'Примечания'

    name = models.CharField(max_length=100, verbose_name='Описание')
    readiness = models.IntegerField(null=True, verbose_name='Готовность')
    priority = models.IntegerField(blank=True, default=0, verbose_name='Приоритет')
    objects = models.Manager()

    def __str__(self):
        return self.name


class DocumentInfo(models.Model):
    class Meta:
        verbose_name = 'Уведомление'
        verbose_name_plural = 'Уведомления'
        ordering = ['id']

    date_placement = models.DateField(blank=False, verbose_name='Дата')
    num_item = models.CharField(max_length=30, unique=True, null=True, db_index=True, verbose_name='№ УВР')
    num_transport = models.CharField(max_length=255, blank=False, null=True, db_index=True, verbose_name='№ авто')
    num_doc = models.CharField(max_length=255, blank=True, null=True, verbose_name='№ документов')
    date_docs = models.CharField(max_length=255, blank=True, null=True, verbose_name='Дата доков')
    documents = models.CharField(max_length=255, blank=True, null=True, verbose_name='Документы')
    status = models.CharField(max_length=255, blank=True, null=True, verbose_name='Статус УВР')
    num_nine = models.CharField(max_length=30, blank=True, null=True, verbose_name='№ Длинной "9"')
    num_td = models.CharField(max_length=50, blank=True, null=True, verbose_name='Таможенное разрешение')
    path_doc = models.CharField(max_length=255, blank=True, null=True, verbose_name='Путь')
    pdf_blob = models.BinaryField(null=True, blank=True, verbose_name='PDF файл')
    objects = models.Manager()

    def __str__(self):
        return self.num_item or ''


class PDFDataBase(models.Model):
    doc_number = models.CharField(max_length=70, unique=True, verbose_name='Номер уведомления')
    full_path = models.CharField(max_length=255, blank=True, verbose_name='Полный путь')
    file_name = models.CharField(max_length=30, blank=True, verbose_name='Имя файла')
    in_use = models.BooleanField(default=False, verbose_name='Путь найден')
    # date_created = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    # date_updated = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    # doc_id = models.OneToOneField('Note', on_delete=models.SET_NULL, null=True, blank=True,
    #                               related_name='uv_doc', verbose_name='Документ')
    objects = models.Manager()

    def __str__(self):
        return self.doc_number or ''


class ERIPDataBase(models.Model):
    id_account = models.CharField(max_length=20, unique=False, null=True, verbose_name='Счёт договора')
    payer_name = models.CharField(max_length=100, unique=False, null=True, verbose_name='ФИО плательщика')
    bill_pay = models.FloatField(null=True, blank=True, verbose_name='Сумма оплаты')
    date = models.DateTimeField(null=True, blank=True, verbose_name='Дата оплаты')
    last_read_time = models.DateTimeField(null=True, blank=True, verbose_name='Время последнего чтения')

    objects = models.Manager()

    def __str__(self):
        return self.id_account or ''

sitelogistic/trade_logistic/views.py
import os
import pandas as pd
import csv

from io import TextIOWrapper

from django.http import FileResponse
from django.contrib.auth import logout, login
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseNotFound, Http404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django_tables2 import SingleTableView, LazyPaginator, RequestConfig
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin

from .forms import *
from .models import *
from .tables import DocTable, DocsFilter, ERIPTable, ERIPFilter
from .utils import *


class TradeLogisticHome(DataMixin, ListView):
    model = TradeLogistic
    template_name = 'trade_logistic/index.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Главная страница')
        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        return TradeLogistic.objects.filter(is_published=True)


class TradeLogisticCategory(DataMixin, ListView):
    model = TradeLogistic
    template_name = 'trade_logistic/index.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Разделы - ' + str(context['posts'][0].cat),
                                      cat_selected=context['posts'][0].cat_id)
        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        return TradeLogistic.objects.filter(cat__slug=self.kwargs['cat_slug'], is_published=True)


class ShowPost(DataMixin, DetailView):
    model = TradeLogistic
    template_name = 'trade_logistic/post.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title=context['post'])
        return dict(list(context.items()) + list(c_def.items()))


class AddPage(LoginRequiredMixin, DataMixin, CreateView):
    form_class = AddPostForm
    template_name = 'trade_logistic/add_page.html'
    success_url = reverse_lazy('home')
    raise_exception = True

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Добавление статьи')
        return dict(list(context.items()) + list(c_def.items()))


def show_category(request, cat_slug):
    category = get_object_or_404(Category, slug=cat_slug)
    posts = TradeLogistic.published.filter(cat_id=category.pk).select_related('cat')
    data = {
        'title': f'Модуль: {category.name}',
        'menu': menu,
        'posts': posts,
        'cat_selected': category.pk
    }
    return render(request, 'trade_logistic/index.html', context=data)


def show_tag_postlist(request, tag_slug):
    tag = get_object_or_404(TagPost, slug=tag_slug)
    posts = tag.tags.filter(is_published=TradeLogistic.Status.PUBLISHED).select_related('cat')
    data = {
        'title': f"Тег: {tag.tag}",
        'menu': menu,
        'posts': posts,
    }
    return render(request, 'trade_logistic/index.html', context=data)


def handle_uploaded_file(file):
    data = []
    reader = csv.reader(TextIOWrapper(file, encoding='utf-8'), delimiter=';')
    for row in reader:
        data.append(row)
    return data


def upload_file(request):
    if request.method == 'POST' and request.FILES['csv_file']:
        csv_file = request.FILES['csv_file']
        data = handle_uploaded_file(csv_file)
        return render(request, 'trade_logistic/display_csv.html', {'data': data})

    return render(request, 'trade_logistic/upload_file.html')


def get_excel(request):
    cap = {
        '№': [], 'Код товара': [], 'Наименование': [], 'Артикул': [], 'Торговая марка': [], 'Производитель': [],
        'Страна': [], 'Ед. изм.': [], 'Кол-во в ед. изм.': [], 'Цена': [], 'Стоимость': [],
        'Вес  нетто': [], 'Вес  брутто': [], 'Доп. код': []
    }
    df = pd.DataFrame(cap)
    pd.set_option('display.colheader_justify', 'center')

    excel_file_path = 'invoice_template.xlsx'
    df.to_excel(excel_file_path, index=False)

    with open(excel_file_path, 'rb') as excel_file:
        response = HttpResponse(excel_file.read(),
                                content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = f'attachment; filename={os.path.basename(excel_file_path)}'

    return response


def page_not_found(request, exception):
    return HttpResponseNotFound("<h1>Страница не найдена</h1>")


def about(request):
    if request.method == 'POST':
        pass
    return render(request, 'trade_logistic/about.html', {'title': 'Немного о нас', 'menu': menu})


def contact(request):
    return HttpResponse(f"Обратная связь")


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'trade_logistic/register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Регистрация')
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'trade_logistic/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Авторизация")
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('home')


def logout_user(request):
    logout(request)
    return redirect('login')


def my_view(request):
    data = DocumentInfo.objects.all()
    return render(request, 'trade_logistic/display_csv.html', {'data': data})


class DocsListView(DataMixin, SingleTableMixin, FilterView):
    model = DocumentInfo
    table_class = DocTable
    template_name = 'trade_logistic/fdb_data.html'
    filterset_class = DocsFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['table'].paginate = False  # Отключаем автоматическую пагинацию
        return dict(list(context.items()))


# def download(request, path_doc):
#     file_path = path_doc
#     response = FileResponse(open(file_path, 'rb'))
#     response['Content-Disposition'] = f'attachment; filename="{file_path.split("/")[-1]}"'
#     return response

def download(request, path_doc):
    file_path = os.path.normpath(path_doc)
    if not os.path.exists(file_path):
        return HttpResponseNotFound(f"File not found: {file_path}")

    file_name = os.path.basename(file_path)  # Извлекаем только имя файла из пути
    with open(file_path, 'rb') as f:
        response = FileResponse(f)
        response['Content-Disposition'] = f'attachment; filename="{file_name}"'
        return response


def show_happy_birthdays(request):
    TXT_FILE = r'D:\khomich\static_sitelogistic\happy_birthdays_bts.txt'
    with open(TXT_FILE, 'r', encoding='utf-8') as file:
        for _ in range(9):  # Пропускаем первые 9 строк
            next(file)

        df = pd.read_csv(file, delimiter='\t', names=['ФИО (полное)', 'Должность', 'Подразделение', 'Дата рождения', 'Возраст'])

    df['Дата рождения'] = pd.to_datetime(df['Дата рождения'], format='%d.%m.%Y')
    now = pd.Timestamp('now')
    df['days_until_birthday'] = (df['Дата рождения'].dt.month - now.month)*30 + df['Дата рождения'].dt.day - now.day
    df.loc[df['days_until_birthday'] < 0, 'days_until_birthday'] += 360
    df = df.sort_values(by='days_until_birthday')

    df = df.drop_duplicates(subset='ФИО (полное)', keep='first')
    df = df.head(20)
    df = df.drop(columns=['days_until_birthday'])

    df['Дата рождения'] = df['Дата рождения'].dt.strftime('%d.%m.%Y')

    html_table = df.to_html()

    return render(
        request,
        'trade_logistic/happy_birthdays.html',
        {'data': html_table}
    )


def erip_info(request):
    erip_filter = ERIPFilter(request.GET, queryset=ERIPDataBase.objects.all())
    table = ERIPTable(erip_filter.qs)
    RequestConfig(request, paginate={'per_page': 15}).configure(table)
    return render(request, 'trade_logistic/erip_info.html', {'table': table, 'filter': erip_filter})

sitelogistic/trade_logistic/templates/trade_logistic/about.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ title }}</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p><input type="file" name="file_upload"></p>
    <p><button type="submit">Отправить</button></p>
</form>
<div class="container">
    <h1>РУП «Белтаможсервис»</h1>
    <ul>
        <li>Дата начала деятельности – 10 июня 1999 года.</li>
        <li>Форма собственности – государственная.</li>
        <li>Организационно-правовая форма – унитарное предприятие.</li>
        <li>Учредитель Предприятия – Государственный таможенный комитет Республики Беларусь.</li>
    </ul>
    <p>Предприятие осуществляет деятельность в качестве:</p>
    <ol>
        <li>Таможенного представителя</li>
        <li>Таможенного перевозчика</li>
        <li>Уполномоченного экономического оператора 3-го типа</li>
    </ol>
    <p>Первоочередной целью создания Предприятия являлось осуществление деятельности в качестве таможенного
        представителя (с 1999 года), в том числе в республиканских пунктах таможенного оформления (с 2001 года).</p>
    <p>За 20 лет РУП «Белтаможсервис» приобрело репутацию надежного партнера, является крупнейшим белорусским
        логистическим оператором. Предприятие отвечает всем требованиям, предъявляемым к логистическим предприятиям
        самого высокого класса, оснащено современной техникой, благодаря которой в своей работе мы используем только
        новейшие информационные технологии. Предоставляем профессиональный сервис, постоянно повышая квалификацию
        сотрудников путем обучения и внедрения новых процессов в работе.</p>
</div>

{% endblock %}

sitelogistic/trade_logistic/templates/trade_logistic/addpage.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<form action="" method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_filed_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-erorr">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Отправить</button></p>
</form>
{% endblock %}

sitelogistic/trade_logistic/templates/trade_logistic/display_csv.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{% url 'load_docs' %}">
    {% csrf_token %}
    <button type="submit">Вызвать функцию</button>
</form>

<div>
    <h1>Содержимое CSV файла</h1>
        <table>
            {% for row in data %}
                <tr>
                    {% for item in row %}
                        <td>{{ item }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
</div>

{% endblock %}

sitelogistic/trade_logistic/templates/trade_logistic/download_button.html
{% if record.path_doc %}
    <form action="{% url 'download' path_doc=record.path_doc %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Скачать</button>
    </form>
{% else %}
    Нет файла для скачивания
{% endif %}

sitelogistic/trade_logistic/templates/trade_logistic/erip_info.html
{% load static %}
{% load django_tables2 %}

<!DOCTYPE html>
<html>
<head>
    <title>ERIP</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'trade_logistic/css/erip_info.css' %}">
</head>
<body>
    <div class="container">
        <h2>ERIP Data Info</h2>
        <form method="get">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_id_account">Счёт договора</label>
                    <input type="text" name="id_account" id="id_id_account" class="form-control">
                </div>
                <div class="form-group col-md-6">
                    <label for="id_payer_name">Ф.И.О плательщика</label>
                    <input type="text" name="payer_name" id="id_payer_name" class="form-control">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_date_after">Дата оплаты (с)</label>
                    <input type="date" name="date_after" id="id_date_after" class="form-control">
                </div>
                <div class="form-group col-md-6">
                    <label for="id_date_before">Дата оплаты (по)</label>
                    <input type="date" name="date_before" id="id_date_before" class="form-control">
                </div>
            </div>
            <button class="btn btn-primary" type="submit">Search</button>
        </form>
        {% render_table table %}
    </div>
</body>
</html>

sitelogistic/trade_logistic/templates/trade_logistic/fdb_data.html
<!-- fdb_data.html -->
{% extends 'base.html' %}
{# trade_logistic/templates/trade_logistic/fdb_data.html #}
<!--{% load render_table from django_tables2 %}-->
{% load render_table from django_tables2 %}
{% load bootstrap3 %}
{% block content %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
$( function() {
    $( ".datepicker" ).datepicker();
} );
</script>

<!--{% render_table table %}-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
{% if filter %}
    <form action="" method="get" class="form form-inline">
        {% bootstrap_form filter.form layout='inline' %}
        {% bootstrap_button 'Отфильтровать' %}
    </form>
{% endif %}
{% render_table table 'django_tables2/bootstrap.html' %}

{% endblock %}

sitelogistic/trade_logistic/templates/trade_logistic/happy_birthdays.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Дни рождения</title>
    <style>
        /* Добавьте здесь свои стили для таблицы */
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
        }
        th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #4CAF50;
            color: white;
        }
    </style>
</head>
<body>
    {{ data|safe }}
</body>
</html>

sitelogistic/trade_logistic/templates/trade_logistic/index.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-articles">
	{% for p in posts %}
	<li><div class="article-panel">
		<p class="first">Категория: {{p.cat.name}}</p>
		<p class="last">Дата: {{p.time_update|date:"d-m-Y H:i:s"}}</p>
	</div>
		<h2>{{p.title}}</h2>
		{% autoescape off %}
		{{p.content|linebreaks|truncatewords:40}}
		{% endautoescape %}
		<div class="clear"></div>
		<p class="link-read-post"><a href="{{ p.get_absolute_url }}">Читать пост</a></p>
	</li>
	{% endfor %}
</ul>
{% endblock %}

sitelogistic/trade_logistic/templates/trade_logistic/list_categories.html
{% for cat in cats %}
    {% if cat.id == cat_selected %}
        <li class="selected">{{ cat.name }}</li>
    {% else %}
        <li><a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a></li>
    {% endif %}
{% endfor %}

sitelogistic/trade_logistic/templates/trade_logistic/list_tags.html
{% if tags %}
    <p>Теги:</p>
    <ul class="tags-list">
        {% for t in tags %}
            <li><a href="{{ t.get_absolute_url }}">{{ t.tag }}</a></li>
        {% endfor %}
    </ul>
{% endif %}

sitelogistic/trade_logistic/templates/trade_logistic/login.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

<div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Войти</button>
</form>

{% endblock %}

sitelogistic/trade_logistic/templates/trade_logistic/post.html
{% extends 'base.html' %}

{% block breadcrumbs %}
{% with post.tags.all as tags %}
{% if tags %}
    <ul class="tags-list">
    <li>Теги:</li>
    {% for t in tags %}
    <li><a href="{{ t.get_absolute_url }}">{{ t.tag }}</a> </li>
    {% endfor %}
    </ul>
{% endif %}
{% endwith %}
{% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>

{% if post.photo %}
    <p> <img class="img-article-left" src="{{ post.photo.url }}"></p>
{% endif %}

{{ post.content|linebreaks }}
{% endblock %}

sitelogistic/trade_logistic/templates/trade_logistic/register.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Регистрация</button>
</form>

{% endblock %}

sitelogistic/trade_logistic/templates/trade_logistic/upload_file.html
{% extends 'base.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p><input type="file" name="csv_file"></p>
    <p><button type="submit">Загрузить CSV файл</button></p>
</form>

<form method="POST" action="">
    {% csrf_token %}
    <button type="submit">Вызвать функцию</button>
</form>

{% if data %}
    <ul>
        {% for item in data %}
            <li>{{ item }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>Нет данных</p>
{% endif %}

{% endblock %}